import string
import json


def load_json(path):
    return json.load(open(path, "rt"))


config = {
    "regex_doublets": r"\b(\w+)\b\s+\b(\1)\b",
    "allowed_chars": string.printable + "ÄÖÜäöüß",
    "strip": [
        r"(\\cite\{[^\}]*\})",
        r"(\\todo\{[^\}]*\})"
    ],
    "evil_twins": [
        (False, "public key",      ["public-key"]),
        (False, "public keys",     ["public-keys"]),
        (False, "elliptic curve",  ["elliptic-curve"]),
        (False, "elliptic curves", ["elliptic-curves"]),
        (True,  "ECC",             ["ecc"]),
        (True,  "RSA",             ["rsa", "Rsa"])
    ],
    "wrong_abbrev": [
        (False, "et al.", [r"(et\.\s*al\.*|et\s+al[^\.])"]),
        (False, "i.e.",   [r"(i\.e[^\.]|ie\.|i\.\s+e\.)"]),
        (False, "e.g.",   [r"(e\.g[^\.]|eg\.|e\.\s+g\.)"])
    ],
    "confusing_words": [
        (False, "threat",   ["thread"]),
        (False, "proposed", ["purposed"]),
        (False, None,       ["lack", "leak", "lacks", "leaks"])
    ],
    "leftover_words": [
        "todo",
        "tbd",
        "fixme",
        "unfinished"
    ],
    "weasel_words": [
        "many",
        "various",
        "very",
        "fairly",
        "several",
        "extremely",
        "exceedingly",
        "quite",
        "remarkably",
        "few",
        "surprisingly",
        "mostly",
        "largely",
        "huge",
        "tiny",
        r"\b((are|is) a number)\b",
        "excellent",
        "interestingly",
        "significantly",
        "substantially",
        "clearly",
        "vast",
        "relatively",
        "completely"
    ],
    "passive_voice": [
        "awoken",
        "been",
        "born",
        "beat",
        "become",
        "begun",
        "bent",
        "beset",
        "bet",
        "bid",
        "bidden",
        "bound",
        "bitten",
        "bled",
        "blown",
        "broken",
        "bred",
        "brought",
        "broadcast",
        "built",
        "burnt",
        "burst",
        "bought",
        "cast",
        "caught",
        "chosen",
        "clung",
        "come",
        "cost",
        "crept",
        "cut",
        "dealt",
        "dug",
        "dived",
        "done",
        "drawn",
        "dreamt",
        "driven",
        "drunk",
        "eaten",
        "fallen",
        "fed",
        "felt",
        "fought",
        "found",
        "fit",
        "fled",
        "flung",
        "flown",
        "forbidden",
        "forgotten",
        "foregone",
        "forgiven",
        "forsaken",
        "frozen",
        "gotten",
        "given",
        "gone",
        "ground",
        "grown",
        "hung",
        "heard",
        "hidden",
        "hit",
        "held",
        "hurt",
        "kept",
        "knelt",
        "knit",
        "known",
        "laid",
        "led",
        "leapt",
        "learnt",
        "left",
        "lent",
        "let",
        "lain",
        "lighted",
        "lost",
        "made",
        "meant",
        "met",
        "misspelt",
        "mistaken",
        "mown",
        "overcome",
        "overdone",
        "overtaken",
        "overthrown",
        "paid",
        "pled",
        "proven",
        "put",
        "quit",
        "read",
        "rid",
        "ridden",
        "rung",
        "risen",
        "run",
        "sawn",
        "said",
        "seen",
        "sought",
        "sold",
        "sent",
        "set",
        "sewn",
        "shaken",
        "shaven",
        "shorn",
        "shed",
        "shone",
        "shod",
        "shot",
        "shown",
        "shrunk",
        "shut",
        "sung",
        "sunk",
        "sat",
        "slept",
        "slain",
        "slid",
        "slung",
        "slit",
        "smitten",
        "sown",
        "spoken",
        "sped",
        "spent",
        "spilt",
        "spun",
        "spit",
        "split",
        "spread",
        "sprung",
        "stood",
        "stolen",
        "stuck",
        "stung",
        "stunk",
        "stridden",
        "struck",
        "strung",
        "striven",
        "sworn",
        "swept",
        "swollen",
        "swum",
        "swung",
        "taken",
        "taught",
        "torn",
        "told",
        "thought",
        "thrived",
        "thrown",
        "thrust",
        "trodden",
        "understood",
        "upheld",
        "upset",
        "woken",
        "worn",
        "woven",
        "wed",
        "wept",
        "wound",
        "won",
        "withheld",
        "withstood",
        "wrung",
        "written"
    ],
    "checks": [
        "check_allowed_chars",
        "check_doubled_words",
        "check_abbrev",
        "check_evil_twins",
        "check_weasel_words",
        "check_passive_voice",
        "check_leftover_words",
        "check_confusing",
    ]
}
